name: Pygbag Web Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Web Version
        run: |
          pip install pygbag
          pygbag --build $GITHUB_WORKSPACE/main.py
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
